spring:
  application:
    name: auth-platform-backend

  datasource:
    url: [DB_URL]
    username: [DB_USERNAME]
    password: [DB_PASSWORD]
    driver-class-name: com.mysql.cj.jdbc.Driver

application:
  security:
    jwt:
      secret-key: [JWT_SECRET]
      access-token-expiration: 900000 # 15 min
      refresh-token-expiration: 3600000 # 1hr OR 60 min

    otp:
      seed: [OTP_GEN_SEED]
      otp-expiration: 300 # 5 min = 300 sec

  email:
    resend:
      api-key: [API]
      from-email: [RESEND_TESTING_EMAIL] #onboarding@resend.dev for RESEND